apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx  # Added space after hyphen
          image: swappykhot/app1
          ports:
            - containerPort: 80  # Changed 'container' to 'containerPort'

